### ISSUE TITLE
Submodule Links 

### ISSUE THREAD

**Issue by a-umar** [OpenDashboardUI/OpenDashboardBackend#7]
To improve the usability the https-links of the submodules in [.gitmodules ](https://github.com/OpenDashboardUI/OpenDashboardBackend/blob/8101e4b/.gitmodules) should be used.
`https://github.com/OpenDashboardUI/OpenDashboardIdl.git`
and
`https://github.com/twyleg/svg_layer_extractor.git`
This would avoid the need for a GitHub account to clone the repository.

**Comment by twyleg** [comment]
Changed
